# Generated by Django 4.0.2 on 2022-03-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='collections',
            field=models.ManyToManyField(related_name='videos', to='videos.Collection'),
        ),
    ]
